"""
Django settings for Demo project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bgtz^3_c*cgpfv(@s^^(crev^c05^ca#%y2ot6)4w*6db4lg!6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'swampdragon',
    'apps.backend',
    'apps.account',
    'apps.chat',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'apps/backend/templates/'),
            os.path.join(BASE_DIR, 'apps/account/templates/'),
            os.path.join(BASE_DIR, 'apps/chat/templates/'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Demo.context_processors.baseUrl',
                'Demo.context_processors.staticUrl'
            ],
        },
    },
]

WSGI_APPLICATION = 'Demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-TW'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_BACKEND_ROOT = os.path.join(BASE_DIR, 'apps/backend/static')
STATIC_CHAT_ROOT = os.path.join(BASE_DIR, 'apps/chat/static')

STATICFILES_DIRS = [['backend_script', os.path.join(STATIC_BACKEND_ROOT, 'script')],
                    ("backend_css", os.path.join(STATIC_BACKEND_ROOT, 'css')),
                    ("backend_view", os.path.join(STATIC_BACKEND_ROOT, 'view')),
                    ("backend_knockout", os.path.join(STATIC_BACKEND_ROOT, 'knockout')),
                    ("images", os.path.join(STATIC_ROOT, 'images')),
                    ("chat", STATIC_CHAT_ROOT),]

LOGIN_REDIRECT_URL = '/backend/'
LOGIN_URL = '/backend/login/'

SESSION_COOKIE_AGE = 3600

# SwampDragon settings
SWAMP_DRAGON_CONNECTION = ('Demo.sockserver.DataConnection', '/data')

DRAGON_URL = 'http://localhost:9999/'

SWAMP_DRAGON = {
    'config_name': 'value',
}